

               expression  ::=  lambdaExpression ;


         lambdaExpression  ::=  "λ"<NO_WHITESPACE>variable<NO_WHITESPACE>":"<NO_WHITESPACE>type<NO_WHITESPACE>"."<NO_WHITESPACE>lambdaExpression

                             |  lambdaExpression lambdaExpression

                             |  "(" lambdaExpression ")"

                             |  variable

                             ;


                 variable  ::=  [name] ;


                     type  ::=  [name] ;
