

                         statement!  ::=  lambdaStatement ;


                    lambdaStatement  ::=  lambdaContext "|-" lambdaExpression 

                                       |  lambdaExpression ":" type 

                                       ;


                      lambdaContext  ::=  variable ;

